#! /usr/bin/env bash

set -e
set -u

___XVS_DEFINE_COMMAND_NAME="xvs"
___XVS_DEFINE_COMMAND_NAMESPACE="xvs/main"

___XVS_DEFINE_COMMAND_EXECUTABLE_PATH="$(readlink "$0" || echo "$0")"
___XVS_DEFINE_COMMAND_EXECUTABLE_LOCATION_PATH="$(dirname "${___XVS_DEFINE_COMMAND_EXECUTABLE_PATH}")"
source "${___XVS_DEFINE_COMMAND_EXECUTABLE_LOCATION_PATH}/.common/define_command.sh"
