#! sh

set -e
set -u

case "${__XVS_RUNTIME_STATE-inactive}" in
  inactive)
    __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"
    __XVS_PROJECT_DIR_PATH="${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/.."
    __XVS_PROJECT_DIR_BIN_NAME="bin"
    __XVS_PROJECT_DIR_BIN_PATH=${__XVS_PROJECT_DIR_PATH}/${__XVS_PROJECT_DIR_BIN_NAME}

    exec ${__XVS_PROJECT_DIR_BIN_PATH}/xvs system bootstrap dependency runtime $@
    ;;

  bootstrapping)
    __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"

    exec ${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/xvs system bootstrap dependency runtime $@
    ;;

  activating)
    echo "xvs-system-bootstrap-dependency-runtime-nix[activating]: TODO" && exit 2
    ;;

  active)
    echo "xvs-system-bootstrap-dependency-runtime-nix[active]: TODO" && exit 2
    ;;

  *)
    echo "invalid state" && exit 1
    ;;
esac

###

if [ ! ${__XVS_RUNTIME_STATE-inactive} == "active" ]; then
  __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"
  __XVS_PROJECT_DIR_PATH="${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/.."
  __XVS_PROJECT_DIR_BIN_NAME="bin"
  __XVS_PROJECT_DIR_BIN_PATH=${__XVS_PROJECT_DIR_PATH}/${__XVS_PROJECT_DIR_BIN_NAME}
  exec ${__XVS_PROJECT_DIR_BIN_PATH}/xvs system bootstrap dependencies runtimes $@
fi

__XVS_SYSTEM_BOOTSTRAP_CACHE_PATH="$(which make)"
__XVS_SYSTEM_BOOTSTRAP_BUILDER_PROGRAM_PATH="${__XVS_PROJECT_PATH}/Makefile"

if [[ $# -ge 1 ]]
then
  exec "${__XVS_SYSTEM_BOOTSTRAP_BUILDER_PATH}" -s -f "${__XVS_SYSTEM_BOOTSTRAP_BUILDER_PROGRAM_PATH}" -C "${__XVS_PROJECT_PATH}" "${1}"
else
  exec "${__XVS_SYSTEM_BOOTSTRAP_BUILDER_PATH}" -s -f "${__XVS_SYSTEM_BOOTSTRAP_BUILDER_PROGRAM_PATH}" -C "${__XVS_PROJECT_PATH}"
fi

