#! sh

set -e
set -u

case "${__XVS_RUNTIME_STATE-inactive}" in
  inactive)
    __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"
    __XVS_PROJECT_DIR_PATH="${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/.."
    __XVS_PROJECT_DIR_BIN_NAME="bin"
    __XVS_PROJECT_DIR_BIN_PATH=${__XVS_PROJECT_DIR_PATH}/${__XVS_PROJECT_DIR_BIN_NAME}

    exec ${__XVS_PROJECT_DIR_BIN_PATH}/xvs system bootstrap dependency $@
    ;;

  bootstrapping)
    __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"

    exec ${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/xvs system bootstrap dependency $@
    ;;

  activating)
    echo "xvs-system-bootstrap-dependency-runtime[activating]: TODO" && exit 2
    ;;

  active)
    echo "xvs-system-bootstrap-dependency-runtime[active]: TODO" && exit 2
    ;;

  *)
    echo "invalid state" && exit 1
    ;;
esac
