#! /usr/bin/env sh

set -e
set -u

if [ ! ${__XVS_RUNTIME_STATE-inactive} == "active" ]; then
  __XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH="$(cd "$(dirname "$(readlink "$0" || echo "$0")")" && pwd)"
  __XVS_PROJECT_DIR_PATH="${__XVS_PROJECT_BOOTSTRAP_DIR_LIBEXEC_PATH}/.."
  __XVS_PROJECT_DIR_BIN_NAME="bin"
  __XVS_PROJECT_DIR_BIN_PATH=${__XVS_PROJECT_DIR_PATH}/${__XVS_PROJECT_DIR_BIN_NAME}
  exec ${__XVS_PROJECT_DIR_BIN_PATH}/xvs system $@
fi
