---
on:
  pull_request:
  push:

jobs:

  xverse--checks-sanity--properties-executable--in_paths-_--delegates-to-xvs-configuration-compatibility-workflow:
    name: "Xverse: Sanity check for the existence and suitability of compatiblity workflow ./configure action executable for configure/make compatibility workflow"

    runs-on: ubuntu-22.04

    steps:
      - name: Prepare codebase for use
        # github.com/actions/checkout@v4.1.7 - released: 2024 June 13 (last checked: 2024 August 4)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Ensure that ./configure file is a symlink to the appropriate XVS implementation for the xvs-system-compatibility-configure XVS action
        run: |-
          if [ ! -e ./configure ]; then;
            echo "./configure must exist and it does not"
            exit 1; fi

          if [ ! -L ./configure ]; then;
            echo "./configure is not a symbolic link and it must be"
            exit 1; fi

          if [ "$(readlink ./configure)" != "lib/Xvs/libexec/xvs-system-compatibility-configure" ]; then;
            echo "./configure must link to the xvs-system-compatibility-configure XVS action and it does not"
            exit 1; fi

  xverse--checks-sanity--properties-effect--workflows-compatibility--actions-configure--variants-gnumake:
    name: "Xverse: Sanity check for compatiblity workflow ./configure action script (Makefile at ./Makefile generated by default) for configure/make compatibility workflow (GNUMake Variant)"

    needs: xverse--checks-sanity--properties-executable--in_paths-_--delegates-to-xvs-configuration-compatibility-workflow

    runs-on: ubuntu-22.04

    steps:
      - name: Prepare codebase for use
        # github.com/actions/checkout@v4.1.7 - released: 2024 June 13 (last checked: 2024 August 4)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Run ./configure (with no arguments) to generate the (GNU)Makefile at ./Makefile
        run: |-
          ./configure

      - name: Ensure the ./Makefile file expected by the GNUMake executable is present in the project root directory ./
        # github.com/andstor/file-existence-action@v3.0.0 - released: 2024 January 29 (last checked: 2024 August 4)
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6
        with:
          fail: true
          files: "Makefile"
