---
on:
  pull_request:
  push:

jobs:
  xvs--checks-sanity--properties--paths-bin--only-expected-executables-exist:
    name: 'XVS: Sanity check for the presence of only expected executables within the end-user visible path'
    id: properties-only-expected-executables-exist-in-bin

    runs-on: ubuntu-22.04

    steps:
      - name: Prepare codebase for use
        # github.com/actions/checkout@v4.1.7 - released: 2024 June 13 (last checked: 2024 August 4)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: "Check if files, other than expected executables ( 'xvs' ), exist"
        id: check_if_files_other_than_xvs_exist
        # github.com/andstor/file-existence-action@v3.0.0 - released: 2024 January 29 (last checked: 2024 August 4)
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6
        with:
          files: "!./lib/xvs/bin/xvs, ./lib/xvs/bin/*"

      - name: "Files other than expected executables exist"
        if: steps.check_if_files_other_than_xvs_exist.outputs.files_exists == 'true'
        run: |
          echo "XVS: Files other than expected executables ( 'xvs' ) exist in the end-user visible path ./lib/xvs/bin" && exit 1

  xvs--checks-sanity--heuristics--paths-bin--languages-shell_posix:
    name: 'XVS: Sanity check using heuristics (form, usage, portability) for end-user PATH intended executables (in the shell/POSIX language)'

    needs: properties-only-expected-executables-exist-in-bin
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare codebase for use
        # github.com/actions/checkout@v4.1.7 - released: 2024 June 13 (last checked: 2024 August 4)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: "Lint shell code in ./lib/xvs/bin using ShellCheck v0.10.0
        # github.com/ludeeus/action-shellcheck@v2.0.0 - released: 2023 January 30 (last checked: 2024 August 4)
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          version: v0.10.0
          scandir: './lib/xvs/bin'
          SHELLCHECK_OPTS: >-
            -s sh

  xvs--checks-sanity--heuristics-syntax--paths-libexec_bootstrap--languages-shell_posix:
    name: 'XVS: Lint Bootstrap Shell Scripts with ShellCheck (libexec.bootstrap - POSIX Portable Shell Only)'

    runs-on: ubuntu-22.04

    steps:
      - name: Prepare codebase for use
        # github.com/actions/checkout@v4.1.7 - released: 2024 June 13 (last checked: 2024 August 4)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          version: 'v0.10.0'
          scandir: './lib/xvs/lib/libexec.bootstrap'
          SHELLCHECK_OPTS: >-
            -s sh

  xvs--checks-sanity--heuristics-syntax--paths-libexec--languages-shell_zsh:
    name: 'XVS: Lint Bootstrap Shell Scripts with ShellCheck (libexec - Isolated Nix-shell Enabled ZSH-compatible Version Pinned Shell Execution Environment)'

    runs-on: ubuntu-22.04

    steps:
      - name: Prepare codebase for use
        # github.com/actions/checkout@v4.1.7 - released: 2024 June 13 (last checked: 2024 August 4)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Lint shell code in ./lib/xvs/bin using ShellCheck v0.10.0
        # github.com/ludeeus/action-shellcheck@v2.0.0 - released: 2023 January 30 (last checked: 2024 August 4)
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          version: 'v0.10.0'
          scandir: './lib/xvs/lib/libexec'
          SHELLCHECK_OPTS: >-
            -s zsh
